{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-mount-healer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-mount-healer.labels" . | nindent 4 }}
{{- end }}
